apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  password: cG9zdGdyZXM=  # base64 encoded 'postgres'
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws-access-key-id: your-base64-encoded-key
  aws-secret-access-key: your-base64-encoded-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-credentials
type: Opaque
data:
  api-key: your-base64-encoded-key